### ISSUE TITLE
Add ability to disable rooms temporarily

### ISSUE THREAD

**Issue by virtualzone** [seatsurfing/seatsurfing#390]
Some rooms only exist temporarily or can only be booked from time to time. This could be the case e.g. during renovations. Instead of deleting rooms while they can't be booked, it would be nicer if we could disable them to keep their booking history.

**Comment by virtualzone** [comment]
Will be released with v1.21

**Comment by IdanYaffe** [comment]
That is a great feature to have! Thanks for adding it!
I think this would be much more powerful and useful if there was an option to enable or disable those tables/areas during a specific timeframe.
Example: marking an office space as disabled during bank holidays or for an important meeting.
